"""Emit a pure-SQL file that INSERTs every static-GK seed question into
the production ``quiz_questions`` table.

Why a SQL file rather than SQLAlchemy?
--------------------------------------
The production / CI environment has ``psql`` but may not have Python
dependencies installed. A single SQL file can be piped into psql directly::

    psql "$PRODUCTION_DB_URL" -v ON_ERROR_STOP=1 \
        -f backend/seeds/_load/quiz_questions.sql

Idempotency
-----------
Each row uses a deterministic UUID derived from its seed ``id`` string
(uuid5 with namespace ``11111111-0000-0000-0000-000000000004`` — same as
``load_seeds.py`` uses). Statement is ``INSERT ... ON CONFLICT (id) DO NOTHING``
so re-running is a safe no-op.

Usage
-----
    python3 -m scripts.mock_gen.emit_seed_sql
    # writes backend/seeds/_load/quiz_questions.sql

No external deps — pure stdlib (uuid, json, pathlib).
"""
from __future__ import annotations

import json
import re
import sys
import uuid as _uuid
from pathlib import Path

_BACKEND = Path(__file__).resolve().parents[2]
_SEEDS = _BACKEND / "seeds"
_POOL = _SEEDS / "static_gk"
_OUT_DIR = _SEEDS / "_load"
_OUT_FILE = _OUT_DIR / "quiz_questions.sql"

_NS_QUIZ_Q = _uuid.UUID("11111111-0000-0000-0000-000000000004")


def _uuid_for(seed_id: str) -> _uuid.UUID:
    return _uuid.uuid5(_NS_QUIZ_Q, seed_id)


def _sql_escape(s: str | None) -> str:
    """SQL-safe literal quoting. Handles None → NULL, escapes embedded quotes."""
    if s is None:
        return "NULL"
    s = str(s).replace("'", "''")
    return f"'{s}'"


def _json_literal(obj) -> str:
    """Serialise a Python dict/list as a JSON string literal for a JSONB column."""
    body = json.dumps(obj, ensure_ascii=False)
    body = body.replace("'", "''")
    return f"'{body}'"


def emit() -> int:
    _OUT_DIR.mkdir(parents=True, exist_ok=True)

    rows = 0
    with _OUT_FILE.open("w", encoding="utf-8") as fh:
        fh.write("-- Auto-generated by scripts/mock_gen/emit_seed_sql.py\n")
        fh.write("-- Every row has a deterministic UUID (uuid5 from its seed id).\n")
        fh.write("-- ON CONFLICT DO NOTHING makes re-runs a safe no-op.\n\n")
        fh.write("BEGIN;\n\n")

        for bundle_file in sorted(_POOL.rglob("*.json")):
            if bundle_file.name.startswith("_"):
                continue
            try:
                doc = json.loads(bundle_file.read_text(encoding="utf-8"))
            except Exception as e:
                print(f"  SKIP {bundle_file}: {e}", file=sys.stderr)
                continue
            bundle_subject = doc.get("subject") or "General Knowledge"
            bundle_topic = doc.get("topic")
            bundle_tc = doc.get("topic_code")
            questions = doc.get("questions") or []
            if not questions:
                continue
            fh.write(f"-- {bundle_file.relative_to(_SEEDS)} ({len(questions)} Qs)\n")
            for q in questions:
                qid = q.get("id")
                if not qid:
                    continue
                q_uuid = _uuid_for(qid)
                stem = q.get("stem") or ""
                expl = q.get("explanation") or ""
                difficulty = (q.get("difficulty") or "MEDIUM").upper()
                subject = q.get("subject") or bundle_subject
                topic = q.get("topic") or bundle_topic
                topic_code = q.get("topic_code") or bundle_tc
                options = q.get("options") or []
                sql = (
                    "INSERT INTO quiz_questions "
                    "(id, question_text, image_url, explanation, difficulty, subject, topic, topic_code, options, created_at) "
                    "VALUES ("
                    f"'{q_uuid}', "
                    f"{_sql_escape(stem)}, "
                    f"NULL, "
                    f"{_sql_escape(expl)}, "
                    f"{_sql_escape(difficulty)}, "
                    f"{_sql_escape(subject)}, "
                    f"{_sql_escape(topic)}, "
                    f"{_sql_escape(topic_code)}, "
                    f"{_json_literal(options)}, "
                    f"NOW()"
                    ") ON CONFLICT (id) DO NOTHING;\n"
                )
                fh.write(sql)
                rows += 1
            fh.write("\n")

        fh.write("\nCOMMIT;\n")
        fh.write(f"\n-- Emitted {rows} INSERTs.\n")

    print(f"wrote {_OUT_FILE.relative_to(_BACKEND)} with {rows} INSERTs")
    return 0


if __name__ == "__main__":
    sys.exit(emit())
