# Expanded Taxonomy Mapping for Pariksha365 (250+ granular topics)
# Format: (Subject, Topic Display Name, Topic Code, [Aliases])

TAXONOMY_EXPANDED = [
    # ─── Polity & Governance (Expanded) ───
    ("Polity", "Historical Underpinnings & Making", "POL_HISTORY", ["making of constitution", "historical background"]),
    ("Polity", "Preamble & Philosophy", "POL_PREAMBLE", ["preamble", "philosophy of constitution"]),
    ("Polity", "Union & Its Territory", "POL_UNION_TERRITORY", ["union territory", "territory of india"]),
    ("Polity", "Citizenship", "POL_CITIZENSHIP", ["citizenship"]),
    ("Polity", "Fundamental Rights", "POL_FR", ["fundamental rights", "part iii"]),
    ("Polity", "Directive Principles (DPSP)", "POL_DPSP", ["dpsp", "directive principles", "part iv"]),
    ("Polity", "Fundamental Duties", "POL_FD", ["fundamental duties", "part iv-a", "article 51a"]),
    ("Polity", "President", "POL_PRESIDENT", ["president"]),
    ("Polity", "Vice-President", "POL_VP", ["vice president"]),
    ("Polity", "Prime Minister & Council of Ministers", "POL_PM_COM", ["prime minister", "council of ministers"]),
    ("Polity", "Parliament - Lok Sabha", "POL_LOK_SABHA", ["lok sabha", "lower house"]),
    ("Polity", "Parliament - Rajya Sabha", "POL_RAJYA_SABHA", ["rajya sabha", "upper house"]),
    ("Polity", "Parliamentary Committees", "POL_PARL_COM", ["parliamentary committees", "pac", "estimates committee"]),
    ("Polity", "Governor", "POL_GOVERNOR", ["governor"]),
    ("Polity", "CM & State Council of Ministers", "POL_CM_COM", ["chief minister", "state com"]),
    ("Polity", "State Legislature", "POL_STATE_LEG", ["state legislature", "vidhan sabha", "vidhan parishad"]),
    ("Polity", "Supreme Court", "POL_SC", ["supreme court", "sc"]),
    ("Polity", "High Courts", "POL_HC", ["high court", "hc"]),
    ("Polity", "Subordinate Courts & Lok Adalats", "POL_SUB_COURTS", ["district courts", "lok adalat", "subordinate courts"]),
    ("Polity", "Panchayati Raj", "POL_PANCHAYAT", ["panchayati raj", "73rd amendment", "local self government"]),
    ("Polity", "Municipalities", "POL_MUNICIPALITY", ["municipality", "74th amendment", "urban local bodies"]),
    ("Polity", "Centre-State Relations", "POL_CENTRE_STATE", ["centre state relations"]),
    ("Polity", "Inter-State Relations", "POL_INTER_STATE", ["inter state relations", "zonal councils", "inter state water disputes"]),
    ("Polity", "Emergency Provisions", "POL_EMERGENCY", ["emergency", "national emergency", "president's rule"]),
    ("Polity", "Election Commission", "POL_ELECTION_COM", ["election commission", "eci"]),
    ("Polity", "UPSC & SPSC", "POL_UPSC", ["upsc", "state psc", "public service commission"]),
    ("Polity", "Finance Commission", "POL_FINANCE_COM", ["finance commission", "finance comm"]),
    ("Polity", "Comptroller and Auditor General (CAG)", "POL_CAG", ["cag", "comptroller and auditor general"]),
    ("Polity", "Attorney & Advocate General", "POL_AG", ["attorney general", "advocate general"]),
    ("Polity", "NITI Aayog & Non-Constitutional Bodies", "POL_NITI", ["niti aayog", "planning commission", "ndc"]),
    ("Polity", "NHRC & SHRC", "POL_NHRC", ["nhrc", "human rights commission"]),
    ("Polity", "CBI, CVC & Lokpal", "POL_CBI_CVC_LOKPAL", ["cbi", "cvc", "lokpal", "lokayukta"]),
    ("Polity", "Official Languages", "POL_LANGUAGES", ["official language"]),
    ("Polity", "Constitutional Amendments", "POL_AMENDMENTS", ["amendments", "article 368"]),
    ("Polity", "Schedules & Parts of Constitution", "POL_SCHEDULES", ["schedules", "parts of constitution"]),
    ("Polity", "Special Provisions for SC/ST/OBC/Minorities", "POL_SPECIAL_PROV", ["special provisions", "ncsc", "ncst", "ncbc"]),

    # ─── History (Expanded) ───
    ("History", "Stone Age (Paleolithic/Mesolithic/Neolithic)", "HIS_STONE_AGE", ["stone age", "paleolithic", "mesolithic", "neolithic"]),
    ("History", "Indus Valley Civilization", "HIS_INDUS", ["indus valley", "harappan civilization"]),
    ("History", "Early & Later Vedic Age", "HIS_VEDIC", ["vedic age", "rig veda", "later vedic"]),
    ("History", "Mahajanapadas & Magadha", "HIS_MAHAJANAPADA", ["mahajanapada", "magadha", "nanda dynasty", "haryanka"]),
    ("History", "Buddhism", "HIS_BUDDHISM", ["buddhism", "gautam buddha"]),
    ("History", "Jainism", "HIS_JAINISM", ["jainism", "mahavira"]),
    ("History", "Mauryan Empire", "HIS_MAURYA", ["maurya", "ashoka", "chandragupta"]),
    ("History", "Post-Mauryan & Foreign Invasions", "HIS_POST_MAURYA", ["post mauryan", "sunga", "kanva", "kushana"]),
    ("History", "Sangam Age", "HIS_SANGAM", ["sangam age", "sangam literature"]),
    ("History", "Gupta Empire", "HIS_GUPTA", ["gupta empire", "samudragupta", "chandragupta ii"]),
    ("History", "Harshavardhana & Regional States", "HIS_HARSHA", ["harshavardhana", "pushyabhuti"]),
    ("History", "Cholas, Cheras, Pandyas", "HIS_CHOLA", ["chola", "chera", "pandya"]),
    ("History", "Pallavas & Chalukyas", "HIS_PALLAVA", ["pallava", "chalukya"]),
    ("History", "Rajput Kingdoms", "HIS_RAJPUT", ["rajput", "tripartite struggle"]),
    ("History", "Delhi Sultanate - Slave & Khilji", "HIS_SULTANATE_EARLY", ["delhi sultanate", "slave dynasty", "khilji"]),
    ("History", "Delhi Sultanate - Tughlaq, Sayyid, Lodi", "HIS_SULTANATE_LATE", ["tughlaq", "sayyid", "lodi"]),
    ("History", "Vijayanagara & Bahmani Kingdoms", "HIS_VIJAYANAGARA", ["vijayanagara", "bahmani", "krishnadevaraya"]),
    ("History", "Bhakti Movement", "HIS_BHAKTI", ["bhakti movement"]),
    ("History", "Sufi Movement", "HIS_SUFI", ["sufi movement"]),
    ("History", "Mughal Empire - Babur to Akbar", "HIS_MUGHAL_EARLY", ["mughal early", "babur", "humayun", "akbar", "sher shah"]),
    ("History", "Mughal Empire - Jahangir to Aurangzeb", "HIS_MUGHAL_LATE", ["mughal late", "jahangir", "shah jahan", "aurangzeb"]),
    ("History", "Later Mughals & Decline", "HIS_LATER_MUGHALS", ["later mughals", "decline of mughals"]),
    ("History", "Maratha Empire", "HIS_MARATHA", ["maratha", "shivaji", "peshwa"]),
    ("History", "Advent of Europeans", "HIS_EUROPEANS", ["advent of europeans", "portuguese", "dutch", "french"]),
    ("History", "British Conquest (Bengal/Mysore/Marathas/Sikhs)", "HIS_BRITISH_CONQUEST", ["british conquest", "battle of plassey", "buxar", "anglo mysore", "anglo maratha", "anglo sikh"]),
    ("History", "Economic & Social Impact of British Rule", "HIS_ECO_IMPACT", ["economic impact", "land revenue", "permanent settlement", "ryotwari", "mahalwari", "commercialization of agriculture"]),
    ("History", "Revolt of 1857", "HIS_REVOLT_1857", ["revolt of 1857", "sepoy mutiny", "first war of independence"]),
    ("History", "Socio-Religious Reform Movements", "HIS_REFORMS", ["reform movements", "brahmo samaj", "arya samaj", "raja ram mohan roy"]),
    ("History", "Peasant & Tribal Movements", "HIS_PEASANT_TRIBAL", ["peasant movements", "tribal movements", "santhal rebellion", "munda", "indigo revolt"]),
    ("History", "INC Formation & Moderate Phase", "HIS_INC_MODERATES", ["indian national congress", "inc", "moderate phase", "dadabhai naoroji"]),
    ("History", "Extremist Phase & Swadeshi Movement", "HIS_EXTREMISTS", ["extremist phase", "swadeshi movement", "surat split"]),
    ("History", "Revolutionary Terrorism", "HIS_REVOLUTIONARY", ["revolutionary terrorism", "bhagat singh", "anushilan samiti", "gadar party"]),
    ("History", "Gandhian Era - Non-Cooperation & CDS", "HIS_GANDHI_EARLY", ["gandhi", "non cooperation", "civil disobedience", "ncm", "cdm", "salt march"]),
    ("History", "Gandhian Era - Quit India to Independence", "HIS_GANDHI_LATE", ["quit india", "qim", "cabinet mission", "mountbatten plan"]),
    ("History", "INA & Subhash Chandra Bose", "HIS_INA", ["ina", "subhash chandra bose", "azad hind fauj"]),
    ("History", "Constitutional Developments (Acts 1773-1935)", "HIS_CONST_ACTS", ["regulating act", "charter acts", "morley minto", "montagu chelmsford", "goi act 1935"]),
    ("History", "Governors-General & Viceroys", "HIS_VICEROYS", ["governors general", "viceroys"]),
    ("History", "Post-Independence Consolidation", "HIS_POST_INDEP", ["post independence", "integration of states", "nehru era", "reorganization of states"]),
    ("History", "Art & Architecture - Ancient", "HIS_ART_ANCIENT", ["ancient art", "architecture", "cave temples", "stupa", "rock cut"]),
    ("History", "Art & Architecture - Medieval to Modern", "HIS_ART_MEDIEVAL", ["medieval art", "indo-islamic architecture", "mughal architecture"]),
    ("History", "World History - Revolutions", "HIS_WORLD_REV", ["french revolution", "russian revolution", "american revolution", "industrial revolution"]),
    ("History", "World History - World Wars & Cold War", "HIS_WORLD_WARS", ["world war 1", "world war 2", "cold war", "fascism", "nazism"]),

    # ─── Geography (Expanded) ───
    ("Geography", "Solar System & Planets", "GEO_SOLAR", ["solar system", "planets", "universe"]),
    ("Geography", "Earth's Interior", "GEO_EARTH_INTERIOR", ["earth interior", "crust", "mantle", "core"]),
    ("Geography", "Latitudes, Longitudes & Time", "GEO_LAT_LONG", ["latitudes", "longitudes", "time zones", "international date line"]),
    ("Geography", "Rocks & Minerals", "GEO_ROCKS", ["rocks", "minerals", "igneous", "sedimentary", "metamorphic"]),
    ("Geography", "Plate Tectonics & Continental Drift", "GEO_TECTONICS", ["plate tectonics", "continental drift", "seafloor spreading"]),
    ("Geography", "Earthquakes & Volcanoes", "GEO_EARTHQUAKES", ["earthquakes", "volcanoes", "seismic waves", "tsunami"]),
    ("Geography", "Landforms (Fluvial/Glacial/Wind/Coastal)", "GEO_LANDFORMS", ["landforms", "geomorphology", "erosion", "weathering"]),
    ("Geography", "Climatology - Atmosphere Structure & Comp", "GEO_ATMOSPHERE", ["atmosphere structure", "composition of atmosphere"]),
    ("Geography", "Climatology - Insolation & Temperature", "GEO_TEMPERATURE", ["insolation", "temperature distribution", "heat budget"]),
    ("Geography", "Climatology - Pressure & Winds", "GEO_WINDS", ["atmospheric pressure", "planetary winds", "local winds", "jet streams"]),
    ("Geography", "Climatology - Cyclones & Anticyclones", "GEO_CYCLONES", ["cyclones", "anticyclones", "tropical cyclones", "temperate cyclones"]),
    ("Geography", "Climatology - Humidity & Precipitation", "GEO_PRECIPITATION", ["humidity", "precipitation", "rainfall types", "clouds"]),
    ("Geography", "Climatology - World Climate Types (Koppen)", "GEO_CLIMATE_TYPES", ["world climate", "koppen classification"]),
    ("Geography", "Oceanography - Ocean Bottom Morphology", "GEO_OCEAN_RELIEF", ["ocean bottom", "continental shelf", "oceanic trenches"]),
    ("Geography", "Oceanography - Currents & Tides", "GEO_OCEAN_CURRENTS", ["ocean currents", "tides", "waves"]),
    ("Geography", "Oceanography - Salinity & Temperature", "GEO_OCEAN_SALINITY", ["ocean salinity", "ocean temperature"]),
    ("Geography", "India - Location & Extent", "GEO_IND_LOCATION", ["india location", "frontiers", "neighbors"]),
    ("Geography", "India - Himalayas & Northern Mountains", "GEO_IND_HIMALAYAS", ["himalayas", "northern mountains", "passes"]),
    ("Geography", "India - Northern Plains & Peninsular Plateau", "GEO_IND_PLATEAU", ["northern plains", "peninsular plateau", "deccan plateau"]),
    ("Geography", "India - Coastal Plains & Islands", "GEO_IND_COASTS", ["coastal plains", "islands", "andaman", "lakshadweep"]),
    ("Geography", "India - Himalayan River System", "GEO_IND_RIVER_HIM", ["himalayan rivers", "ganga", "indus", "brahmaputra"]),
    ("Geography", "India - Peninsular River System", "GEO_IND_RIVER_PEN", ["peninsular rivers", "godavari", "krishna", "cauvery", "narmada", "tapi"]),
    ("Geography", "India - Climate & Monsoon", "GEO_IND_MONSOON", ["indian climate", "indian monsoon", "seasons"]),
    ("Geography", "India - Natural Vegetation (Forests)", "GEO_IND_FORESTS", ["natural vegetation", "indian forests", "forest resources"]),
    ("Geography", "India - Soils", "GEO_IND_SOILS", ["indian soils", "alluvial", "black soil", "red soil", "laterite"]),
    ("Geography", "India - Agriculture & Cropping Seasons", "GEO_IND_AGRI", ["indian agriculture", "kharif", "rabi", "zaid", "crops", "green revolution"]),
    ("Geography", "India - Mineral Resources", "GEO_IND_MINERALS", ["indian minerals", "iron ore", "bauxite", "copper", "manganese"]),
    ("Geography", "India - Energy Resources (Coal/Oil/Renewable)", "GEO_IND_ENERGY", ["energy resources", "coal", "petroleum", "solar", "wind", "nuclear energy"]),
    ("Geography", "India - Industries", "GEO_IND_INDUSTRIES", ["indian industries", "iron and steel", "textile", "industrial regions"]),
    ("Geography", "India - Transport (Rail/Road/Water/Air)", "GEO_IND_TRANSPORT", ["transport in india", "railways", "national highways", "ports", "waterways"]),
    ("Geography", "India - Demographics & Census 2011", "GEO_IND_CENSUS", ["demographics", "census 2011", "population density", "literacy", "sex ratio"]),
    ("Geography", "World - Continents & Oceans Overview", "GEO_WORLD_OVERVIEW", ["continents", "oceans overview"]),
    ("Geography", "World - Major Mountains, Rivers, Deserts, Lakes", "GEO_WORLD_FEATURES", ["world mountains", "world rivers", "world deserts", "world lakes", "straits", "islands"]),
    ("Geography", "Economic & Human Geography - World", "GEO_ECO_WORLD", ["world economic geography", "human geography", "tribes", "world agriculture"]),
    ("Geography", "Environment - Ecology & Ecosystems", "GEO_ENV_ECOLOGY", ["ecology", "ecosystems", "food chain", "food web", "ecological pyramids"]),
    ("Geography", "Environment - Biodiversity & Conservation", "GEO_ENV_BIODIVERSITY", ["biodiversity", "conservation", "national parks", "wildlife sanctuaries", "biosphere reserves"]),
    ("Geography", "Environment - Pollution & Climate Change", "GEO_ENV_POLLUTION", ["pollution", "climate change", "global warming", "ozone depletion", "greenhouse effect"]),
    ("Geography", "Environment - International Protocols & Conventions", "GEO_ENV_PROTOCOLS", ["international protocols", "kyoto protocol", "montreal protocol", "unfccc", "cbd"]),
    ("Geography", "Straits, Bays and Gulfs", "GEO_STRAITS_BAYS", ["straits", "bays", "gulfs"]),

    # ─── Economics (Expanded) ───
    ("Economics", "Microeconomics Basics", "ECO_MICRO", ["microeconomics", "demand", "supply", "cost", "market structures"]),
    ("Economics", "National Income (GDP, GNP, NNP)", "ECO_NAT_INCOME", ["national income", "gdp", "gnp", "nnp", "per capita income"]),
    ("Economics", "Economic Growth & Development (HDI)", "ECO_GROWTH", ["economic growth", "economic development", "hdi", "happiness index"]),
    ("Economics", "Economic Planning & NITI Aayog", "ECO_PLANNING", ["economic planning", "five year plans", "niti aayog", "planning commission"]),
    ("Economics", "Poverty & Inequality", "ECO_POVERTY", ["poverty", "poverty line", "inequality", "lorenz curve", "gini coefficient"]),
    ("Economics", "Unemployment", "ECO_UNEMPLOYMENT", ["unemployment", "types of unemployment", "employment generation programs"]),
    ("Economics", "Inflation & Business Cycle", "ECO_INFLATION", ["inflation", "cpi", "wpi", "deflation", "stagflation", "business cycle"]),
    ("Economics", "RBI & its Functions", "ECO_RBI", ["rbi", "reserve bank of india", "central bank functions"]),
    ("Economics", "Monetary Policy & Instruments", "ECO_MONETARY", ["monetary policy", "repo rate", "reverse repo", "crr", "slr", "open market operations"]),
    ("Economics", "Commercial Banking System & NPAs", "ECO_BANKING", ["banking system", "commercial banks", "npa", "basel norms", "nbfc"]),
    ("Economics", "Money Market & Capital Market (SEBI/Stock)", "ECO_MARKETS", ["money market", "capital market", "sebi", "stock market", "mutual funds"]),
    ("Economics", "Taxes - Direct & Indirect (GST)", "ECO_TAXES", ["taxes", "direct tax", "indirect tax", "gst", "income tax"]),
    ("Economics", "Central Budget & Fiscal Policy", "ECO_BUDGET", ["budget", "fiscal policy", "fiscal deficit", "revenue deficit", "primary deficit"]),
    ("Economics", "Finance Commission", "ECO_FIN_COM", ["finance commission", "finance comm"]),
    ("Economics", "Balance of Payments (BoP)", "ECO_BOP", ["bop", "balance of payments", "current account", "capital account"]),
    ("Economics", "Foreign Trade & Exchange Rates", "ECO_TRADE", ["foreign trade", "exchange rates", "fdi", "fpi", "currency convertibility"]),
    ("Economics", "International Organisations (IMF, WB, WTO)", "ECO_INTL_ORG", ["imf", "world bank", "wto", "wto agreements", "trtps", "trims"]),
    ("Economics", "Agriculture Sector Issues (MSP, Subsidies)", "ECO_AGRI", ["agriculture economics", "msp", "subsidies", "pds", "food security"]),
    ("Economics", "Industrial Sector & Policies (MSME, PSUs)", "ECO_INDUSTRY", ["industrial sector", "industrial policies", "msme", "psu", "disinvestment", "make in india"]),
    ("Economics", "Services Sector", "ECO_SERVICES", ["services sector", "it sector", "tourism"]),
    ("Economics", "Infrastructure & Energy Economics", "ECO_INFRA", ["infrastructure economics", "energy economics", "transport economics", "ppp models"]),
    ("Economics", "Government Welfare Schemes & Programs", "ECO_SCHEMES", ["government schemes", "welfare programs", "mgnerga", "ayushman bharat", "pm kissan"]),

    # ─── Physics (Expanded) ───
    ("Physics", "Units & Dimensions", "PHY_UNITS", ["units", "dimensions", "si units", "scalar", "vector"]),
    ("Physics", "Motion in 1D & 2D", "PHY_MOTION", ["motion", "displacement", "velocity", "acceleration", "projectile motion"]),
    ("Physics", "Newton's Laws & Friction", "PHY_LAWS", ["newton's laws", "force", "friction", "inertia", "momentum"]),
    ("Physics", "Work, Energy & Power", "PHY_WEP", ["work", "energy", "power", "kinetic energy", "potential energy", "conservation of energy"]),
    ("Physics", "Circular & Rotational Motion", "PHY_ROTATION", ["circular motion", "rotational motion", "torque", "moment of inertia", "centripetal force", "centrifugal force"]),
    ("Physics", "Gravitation & Satellites", "PHY_GRAVITY", ["gravitation", "gravity", "escape velocity", "orbital velocity", "satellites", "kepler's laws"]),
    ("Physics", "Properties of Matter - Elasticity & Fluid Mech", "PHY_FLUIDS", ["elasticity", "fluid mechanics", "pressure", "pascal's law", "archimedes principle", "buoyancy", "bernoulli's theorem"]),
    ("Physics", "Surface Tension & Viscosity", "PHY_SURFACE_TENS", ["surface tension", "viscosity", "capillarity"]),
    ("Physics", "Heat & Thermodynamics", "PHY_HEAT", ["heat", "temperature", "thermodynamics", "specific heat", "latent heat", "conduction", "convection", "radiation"]),
    ("Physics", "Kinetic Theory of Gases", "PHY_KTG", ["kinetic theory of gases", "ideal gas equation"]),
    ("Physics", "Oscillations & SHM", "PHY_SHM", ["oscillations", "simple harmonic motion", "shm", "pendulum"]),
    ("Physics", "Waves & Sound", "PHY_WAVES", ["waves", "sound", "longitudinal waves", "transverse waves", "doppler effect", "echo", "ultrasound"]),
    ("Physics", "Optics - Reflection, Refraction, Lenses", "PHY_OPTICS_1", ["optics", "reflection", "refraction", "mirrors", "lenses", "total internal reflection"]),
    ("Physics", "Optics - Interference, Diffraction, Human Eye", "PHY_OPTICS_2", ["interference", "diffraction", "polarization", "human eye", "defects of vision", "optical instruments"]),
    ("Physics", "Electrostatics", "PHY_ELECTROSTATICS", ["electrostatics", "electric charge", "electric field", "coulomb's law", "capacitance", "electric potential"]),
    ("Physics", "Current Electricity", "PHY_CURRENT", ["current electricity", "ohm's law", "resistance", "electric current", "heating effect of current"]),
    ("Physics", "Magnetic Effects of Current & Magnetism", "PHY_MAGNETISM", ["magnetism", "magnetic field", "magnetic force", "electromagnet", "permanent magnet"]),
    ("Physics", "Electromagnetic Induction & AC", "PHY_EMI_AC", ["electromagnetic induction", "emi", "alternating current", "ac", "transformer", "generator"]),
    ("Physics", "Dual Nature of Matter & Radiation", "PHY_DUAL_NATURE", ["dual nature of matter", "photoelectric effect", "matter waves", "de broglie"]),
    ("Physics", "Atoms & Nuclei", "PHY_ATOMS_NUCLEI", ["atoms", "nuclei", "atomic models", "bohr model"]),
    ("Physics", "Radioactivity & Nuclear Energy", "PHY_RADIOACTIVITY", ["radioactivity", "alpha beta gamma rays", "nuclear fission", "nuclear fusion", "nuclear reactor"]),
    ("Physics", "Semiconductor Electronics", "PHY_SEMICONDUCTORS", ["semiconductors", "p-n junction", "diode", "transistor", "logic gates"]),
    ("Physics", "Communication Systems & Electromagnetic Waves", "PHY_COMMUNICATION", ["communication systems", "em waves", "electromagnetic spectrum"]),

    # ─── Chemistry (Expanded) ───
    ("Chemistry", "Matter - States & Properties", "CHE_MATTER", ["matter", "states of matter", "solid liquid gas", "evaporation", "sublimation"]),
    ("Chemistry", "Atomic Structure", "CHE_ATOMIC_STRUCT", ["atomic structure", "electron", "proton", "neutron", "atomic models", "quantum numbers"]),
    ("Chemistry", "Isotopes, Isobars & Isotones", "CHE_ISOTOPES", ["isotopes", "isobars", "isotones", "radioisotopes"]),
    ("Chemistry", "Periodic Table & Periodicity", "CHE_PERIODIC_TABLE", ["periodic table", "elements", "groups", "periods", "ionization energy", "electronegativity"]),
    ("Chemistry", "Chemical Bonding", "CHE_BONDING", ["chemical bonding", "ionic bond", "covalent bond", "coordinate bond", "hydrogen bond", "van der waals forces"]),
    ("Chemistry", "Acids, Bases & pH", "CHE_ACIDS_BASES", ["acids", "bases", "ph scale", "buffer solutions"]),
    ("Chemistry", "Salts & Indicators", "CHE_SALTS", ["salts", "indicators", "baking soda", "washing soda", "bleaching powder"]),
    ("Chemistry", "Oxidation & Reduction (Redox)", "CHE_REDOX", ["oxidation", "reduction", "redox reactions", "oxidation number", "corrosion", "rancidity"]),
    ("Chemistry", "Thermodynamics in Chemistry", "CHE_THERMO", ["chemical thermodynamics", "exothermic", "endothermic", "enthalpy", "entropy"]),
    ("Chemistry", "Chemical Kinetics & Catalysts", "CHE_KINETICS", ["chemical kinetics", "rate of reaction", "catalyst", "activation energy"]),
    ("Chemistry", "Solutions, Mixtures & Colloids", "CHE_SOLUTIONS", ["solutions", "mixtures", "colloids", "suspensions", "concentration", "solubility"]),
    ("Chemistry", "Separation Techniques", "CHE_SEPARATION", ["separation techniques", "distillation", "chromatography", "crystallization", "filtration"]),
    ("Chemistry", "Gases & Gas Laws", "CHE_GASES", ["gases", "gas laws", "boyle's law", "charles' law", "ideal gas equation"]),
    ("Chemistry", "Metals & Properties", "CHE_METALS", ["metals", "physical properties of metals", "chemical properties of metals", "reactivity series"]),
    ("Chemistry", "Metallurgy (Ores & Extraction)", "CHE_METALLURGY", ["metallurgy", "ores", "extraction of metals", "alloys", "steel", "bronze", "brass"]),
    ("Chemistry", "Non-Metals & their Compounds", "CHE_NON_METALS", ["non-metals", "hydrogen", "oxygen", "nitrogen", "halogens", "inert gases"]),
    ("Chemistry", "Carbon & its Allotropes", "CHE_CARBON", ["carbon", "allotropes of carbon", "diamond", "graphite", "fullerene", "graphene"]),
    ("Chemistry", "Hydrocarbons", "CHE_HYDROCARBONS", ["hydrocarbons", "alkanes", "alkenes", "alkynes", "aromatic compounds"]),
    ("Chemistry", "Organic Chemistry Basics", "CHE_ORGANIC", ["organic chemistry", "functional groups", "isomerism", "nomenclature", "alcohols", "carboxylic acids"]),
    ("Chemistry", "Polymers, Plastics & Fibres", "CHE_POLYMERS", ["polymers", "plastics", "synthetic fibres", "rubber", "nylon", "polythene", "bakelite", "pvc"]),
    ("Chemistry", "Chemistry in Everyday Life", "CHE_EVERYDAY", ["chemistry in everyday life", "soaps", "detergents", "preservatives", "artificial sweeteners", "drugs", "medicines", "explosives", "dyes", "paints"]),
    ("Chemistry", "Cement, Glass & Fertilizers", "CHE_COMMERCIAL", ["cement", "glass", "fertilizers", "npk", "urea"]),

    # ─── Biology (Expanded) ───
    ("Biology", "Branches of Biology & Biologists", "BIO_BRANCHES", ["branches of biology", "famous biologists", "discoveries in biology", "scientific names"]),
    ("Biology", "Cell Structure & Organelles", "BIO_CELL_STRUCT", ["cell structure", "cell organelles", "nucleus", "mitochondria", "ribosomes", "lysosomes", "endoplasmic reticulum", "golgi apparatus", "plastids", "cell wall", "cell membrane"]),
    ("Biology", "Cell Division (Mitosis & Meiosis)", "BIO_CELL_DIVISION", ["cell division", "mitosis", "meiosis", "cell cycle"]),
    ("Biology", "Tissues (Plant & Animal)", "BIO_TISSUES", ["tissues", "plant tissues", "animal tissues", "meristematic", "permanent", "epithelial", "connective", "muscular", "nervous tissue"]),
    ("Biology", "Classification of Living Organisms", "BIO_CLASSIFICATION", ["classification", "taxonomy", "five kingdom classification", "monera", "protista"]),
    ("Biology", "Plant Kingdom (Algae, Fungi, Bryo, Pterido, Gymno, Angio)", "BIO_PLANT_KINGDOM", ["plant kingdom", "algae", "fungi", "bryophytes", "pteridophytes", "gymnosperms", "angiosperms"]),
    ("Biology", "Animal Kingdom Classifications", "BIO_ANIMAL_KINGDOM", ["animal kingdom", "invertebrates", "vertebrates", "phyla", "porifera", "arthropoda", "chordata", "mammals", "birds", "reptiles", "amphibians", "fishes"]),
    ("Biology", "Plant Morphology (Root, Stem, Leaf, Flower, Fruit, Seed)", "BIO_PLANT_MORPH", ["plant morphology", "root", "stem", "leaf", "flower", "fruit", "seed", "inflorescence"]),
    ("Biology", "Plant Physiology - Photosynthesis & Respiration", "BIO_PLANT_PHYS", ["plant physiology", "photosynthesis", "respiration in plants", "transpiration"]),
    ("Biology", "Plant Hormones & Nutrition", "BIO_PLANT_HORMONES", ["plant hormones", "auxins", "gibberellins", "cytokinins", "plant nutrition", "macronutrients", "micronutrients"]),
    ("Biology", "Plant Diseases", "BIO_PLANT_DISEASES", ["plant diseases", "fungal", "bacterial", "viral diseases in plants"]),
    ("Biology", "Human Digestive System", "BIO_DIGESTION", ["digestive system", "digestion", "alimentary canal", "digestive glands", "enzymes", "stomach", "intestine", "liver", "pancreas"]),
    ("Biology", "Human Respiratory System", "BIO_RESPIRATION", ["respiratory system", "respiration", "lungs", "trachea", "alveoli", "breathing"]),
    ("Biology", "Human Circulatory System & Blood", "BIO_CIRCULATION", ["circulatory system", "blood", "heart", "blood groups", "rbc", "wbc", "platelets", "plasma", "blood vessels", "lymphatic system"]),
    ("Biology", "Human Excretory System", "BIO_EXCRETION", ["excretory system", "kidney", "nephron", "urine formation", "lungs", "skin"]),
    ("Biology", "Human Nervous System & Brain", "BIO_NERVOUS", ["nervous system", "brain", "spinal cord", "nerves", "neuron", "reflex action"]),
    ("Biology", "Sense Organs", "BIO_SENSE_ORGANS", ["sense organs", "eye", "ear", "nose", "tongue", "skin"]),
    ("Biology", "Human Endocrine System (Glands & Hormones)", "BIO_ENDOCRINE", ["endocrine system", "glands", "hormones", "pituitary", "thyroid", "adrenal", "pancreas"]),
    ("Biology", "Human Skeletal & Muscular System", "BIO_SKELETAL", ["skeletal system", "muscular system", "bones", "joints", "muscles", "cartilage", "ligaments", "tendons"]),
    ("Biology", "Human Reproductive System", "BIO_REPRODUCTION", ["reproductive system", "male reproductive system", "female reproductive system", "fertilization", "menstrual cycle"]),
    ("Biology", "Nutrition - Carbohydrates, Proteins, Fats", "BIO_NUTRI_MACRO", ["nutrition", "carbohydrates", "proteins", "fats", "lipids", "roughage", "water", "balanced diet"]),
    ("Biology", "Nutrition - Vitamins & Minerals", "BIO_VITAMINS", ["vitamins", "minerals", "vitamin a", "vitamin b complex", "vitamin c", "vitamin d", "vitamin e", "vitamin k", "calcium", "iron", "iodine"]),
    ("Biology", "Human Diseases - Bacterial & Viral", "BIO_DIS_BACTERIAL_VIRAL", ["bacterial diseases", "viral diseases", "tuberculosis", "typhoid", "cholera", "aids", "dengue", "covid"]),
    ("Biology", "Human Diseases - Protozoan, Fungal, Helminthic", "BIO_DIS_OTHER", ["protozoan diseases", "fungal diseases", "helminthic diseases", "malaria", "ringworm", "kala azar", "sleeping sickness"]),
    ("Biology", "Human Diseases - Genetic & Deficiency", "BIO_DIS_GENETIC", ["genetic diseases", "deficiency diseases", "haemophilia", "colour blindness", "down's syndrome", "scurvy", "rickets", "beri beri", "night blindness", "anaemia", "goitre", "kwashiorkor", "marasmus"]),
    ("Biology", "Immunity, Vaccination & Antibiotics", "BIO_IMMUNITY", ["immunity", "vaccination", "antibiotics", "antigens", "antibodies", "active immunity", "passive immunity"]),
    ("Biology", "Genetics & Heredity (Mendel's Laws)", "BIO_GENETICS", ["genetics", "heredity", "mendel's laws", "dna", "rna", "chromosomes", "genes", "mutation"]),
    ("Biology", "Evolution & Origin of Life", "BIO_EVOLUTION", ["evolution", "origin of life", "darwinism", "lamarckism", "human evolution", "fossils"]),
    ("Biology", "Biotechnology & Applications", "BIO_BIOTECH", ["biotechnology", "genetic engineering", "recombinant dna technology", "cloning", "stem cells", "gmo", "bt cotton"]),

    # ─── Science & Technology ───
    ("Science & Technology", "Space Technology & ISRO", "ST_SPACE", ["space technology", "isro", "satellites", "launch vehicles", "pslv", "gslv", "chandrayaan", "mangalyaan", "gaganyaan", "nasa", "esa"]),
    ("Science & Technology", "Defence Technology & Missiles", "ST_DEFENCE", ["defence technology", "drdo", "missiles", "agni", "brahmos", "prithvi", "submarines", "aircraft carriers", "fighter jets", "radars"]),
    ("Science & Technology", "Nuclear Technology", "ST_NUCLEAR", ["nuclear technology", "nuclear power plants in india", "nuclear reactors", "department of atomic energy", "barc"]),
    ("Science & Technology", "IT, Computers & Communications", "ST_IT_COMP", ["information technology", "computers", "communications", "supercomputers", "param", "internet", "5g", "broadband", "optical fibres"]),
    ("Science & Technology", "Nanotechnology & Robotics", "ST_NANO_ROBOTICS", ["nanotechnology", "robotics", "carbon nanotubes", "graphene", "drones"]),
    ("Science & Technology", "Biotechnology Applications", "ST_BIOTECH_APP", ["biotechnology applications", "genome sequencing", "crispr", "dna fingerprinting"]),
    ("Science & Technology", "Recent Discoveries in Science", "ST_DISCOVERIES", ["recent discoveries", "nobel prizes in science"]),

    # ─── Quantitative Aptitude (Expanded) ───
    ("Quantitative Aptitude", "Number System", "QA_NUMBER", ["number system", "types of numbers", "face value", "place value", "unit digit", "remainder theorem"]),
    ("Quantitative Aptitude", "Divisibility Rules", "QA_DIVISIBILITY", ["divisibility rules", "divisibility tests"]),
    ("Quantitative Aptitude", "HCF & LCM", "QA_HCF_LCM", ["hcf", "lcm", "highest common factor", "lowest common multiple"]),
    ("Quantitative Aptitude", "Fractions & Decimals", "QA_FRACTIONS", ["fractions", "decimals", "vulgar fractions", "recurring decimals"]),
    ("Quantitative Aptitude", "Simplification & BODMAS", "QA_SIMPLIFY", ["simplification", "bodmas", "vbodmas", "square roots", "cube roots", "surds", "indices"]),
    ("Quantitative Aptitude", "Percentage", "QA_PERCENT", ["percentage", "successive percentage", "population problems", "election problems"]),
    ("Quantitative Aptitude", "Profit & Loss", "QA_PROFIT_LOSS", ["profit and loss", "cost price", "selling price", "profit percentage", "loss percentage"]),
    ("Quantitative Aptitude", "Discount", "QA_DISCOUNT", ["discount", "marked price", "successive discount", "dishonest dealer"]),
    ("Quantitative Aptitude", "Ratio & Proportion", "QA_RATIO", ["ratio", "proportion", "mean proportional", "third proportional", "fourth proportional", "coins problems"]),
    ("Quantitative Aptitude", "Partnership", "QA_PARTNERSHIP", ["partnership", "investment", "profit share", "active partner", "sleeping partner"]),
    ("Quantitative Aptitude", "Mixture & Alligation", "QA_MIXTURE", ["mixture", "alligation", "replacement of mixture"]),
    ("Quantitative Aptitude", "Problems on Ages", "QA_AGES", ["problems on ages", "age relations"]),
    ("Quantitative Aptitude", "Average", "QA_AVERAGE", ["average", "mean", "weighted average", "batting average", "bowling average"]),
    ("Quantitative Aptitude", "Simple Interest", "QA_SI", ["simple interest", "principal", "rate", "time", "amount"]),
    ("Quantitative Aptitude", "Compound Interest", "QA_CI", ["compound interest", "half yearly", "quarterly", "difference between ci and si", "installments"]),
    ("Quantitative Aptitude", "Time & Work", "QA_TIME_WORK", ["time and work", "efficiency", "alternate days", "leaving work", "wages"]),
    ("Quantitative Aptitude", "Pipes & Cisterns", "QA_PIPES", ["pipes and cisterns", "inlet pipe", "outlet pipe", "leak"]),
    ("Quantitative Aptitude", "Time, Speed & Distance", "QA_TSD", ["time speed and distance", "average speed", "relative speed", "early late problems"]),
    ("Quantitative Aptitude", "Problems on Trains", "QA_TRAINS", ["problems on trains", "crossing a pole", "crossing a platform", "crossing another train"]),
    ("Quantitative Aptitude", "Boats & Streams", "QA_BOATS", ["boats and streams", "upstream", "downstream", "speed of boat in still water", "speed of current"]),
    ("Quantitative Aptitude", "Races & Games", "QA_RACES", ["races", "linear race", "circular track", "giving a start"]),
    ("Quantitative Aptitude", "Algebra", "QA_ALGEBRA", ["algebra", "algebraic identities", "polynomials", "linear equations", "quadratic equations", "roots of equation", "maxima and minima"]),
    ("Quantitative Aptitude", "Trigonometry - Ratios & Identities", "QA_TRIG", ["trigonometry", "trigonometric ratios", "trigonometric identities", "values of trigonometric functions", "maxima and minima in trigonometry", "circular measure", "radians"]),
    ("Quantitative Aptitude", "Heights & Distances", "QA_HEIGHTS", ["heights and distances", "angle of elevation", "angle of depression"]),
    ("Quantitative Aptitude", "Geometry - Lines & Angles", "QA_GEOM_LINES", ["geometry", "lines and angles", "parallel lines", "transversal", "vertically opposite angles", "alternate angles", "corresponding angles", "supplementary angles", "complementary angles"]),
    ("Quantitative Aptitude", "Geometry - Triangles", "QA_GEOM_TRIANGLES", ["triangles", "properties of triangles", "types of triangles", "congruence of triangles", "similarity of triangles", "pythagoras theorem", "centers of triangle", "centroid", "incenter", "circumcenter", "orthocenter"]),
    ("Quantitative Aptitude", "Geometry - Circles & Quadrilaterals", "QA_GEOM_CIRCLES", ["circles", "properties of circles", "chord", "tangent", "secant", "cyclic quadrilateral", "quadrilaterals", "parallelogram", "rectangle", "rhombus", "square", "trapezium", "polygons"]),
    ("Quantitative Aptitude", "Mensuration 2D (Area & Perimeter)", "QA_MEN_2D", ["mensuration 2d", "area", "perimeter", "triangle", "rectangle", "square", "parallelogram", "rhombus", "trapezium", "circle", "sector", "segment"]),
    ("Quantitative Aptitude", "Mensuration 3D (Volume & Surface Area)", "QA_MEN_3D", ["mensuration 3d", "volume", "surface area", "cube", "cuboid", "cylinder", "cone", "sphere", "hemisphere", "frustum", "prism", "pyramid"]),
    ("Quantitative Aptitude", "Coordinate Geometry", "QA_COORD_GEOM", ["coordinate geometry", "distance formula", "section formula", "area of triangle", "slope of line", "equation of line", "collinearity"]),
    ("Quantitative Aptitude", "Data Interpretation (DI)", "QA_DI", ["data interpretation", "tabulation", "bar graphs", "line graphs", "pie charts", "radar graphs", "caselet di", "missing data di"]),
    ("Quantitative Aptitude", "Permutation & Combination", "QA_PNC", ["permutation and combination", "fundamental principle of counting", "factorial", "arrangements", "selections", "circular permutation"]),
    ("Quantitative Aptitude", "Probability", "QA_PROBABILITY", ["probability", "experiment", "event", "sample space", "mutually exclusive events", "independent events", "conditional probability", "coins", "dice", "cards", "balls"]),
    ("Quantitative Aptitude", "Data Sufficiency", "QA_DATA_SUFF", ["data sufficiency"]),

    # ─── Reasoning (Expanded) ───
    ("Reasoning", "Analogy (Word, Number, Letter)", "RSN_ANALOGY", ["analogy", "word analogy", "number analogy", "letter analogy"]),
    ("Reasoning", "Classification / Odd One Out", "RSN_CLASSIFY", ["classification", "odd one out", "word classification", "number classification", "letter classification"]),
    ("Reasoning", "Coding & Decoding", "RSN_CODING", ["coding and decoding", "letter coding", "number coding", "substitution coding", "mixed letter coding", "mixed number coding", "matrix coding"]),
    ("Reasoning", "Series (Number & Letter)", "RSN_SERIES", ["series", "number series", "letter series", "alpha-numeric series", "continuous pattern series"]),
    ("Reasoning", "Blood Relations", "RSN_BLOOD", ["blood relations", "family tree", "coded blood relations", "pointing towards a person"]),
    ("Reasoning", "Direction & Distance", "RSN_DIRECTION", ["direction and distance", "shadow problems", "coded direction sense"]),
    ("Reasoning", "Syllogism", "RSN_SYLLOGISM", ["syllogism", "statements and conclusions", "venn diagram method", "possibility cases", "reverse syllogism"]),
    ("Reasoning", "Venn Diagrams", "RSN_VENN", ["venn diagrams", "logical venn diagrams"]),
    ("Reasoning", "Ranking & Order Test", "RSN_RANKING", ["ranking and order test", "position test", "time sequence test"]),
    ("Reasoning", "Alphabet Test & Dictionary Order", "RSN_ALPHABET", ["alphabet test", "dictionary order", "letter word formation", "jumbled words", "alpha-numeric sequence puzzle"]),
    ("Reasoning", "Mathematical Operations", "RSN_MATH_OPS", ["mathematical operations", "symbol substitution", "balancing the equation", "interchange of signs and numbers"]),
    ("Reasoning", "Inequalities", "RSN_INEQUALITIES", ["inequalities", "coded inequalities", "mathematical inequalities"]),
    ("Reasoning", "Seating Arrangement - Linear", "RSN_SEATING_LINEAR", ["linear seating arrangement", "single row", "double row"]),
    ("Reasoning", "Seating Arrangement - Circular", "RSN_SEATING_CIRCULAR", ["circular seating arrangement", "facing center", "facing outside", "square arrangement", "rectangular arrangement"]),
    ("Reasoning", "Puzzles", "RSN_PUZZLES", ["puzzles", "floor based puzzle", "box based puzzle", "scheduling puzzle", "day/month/year puzzle", "classification puzzle"]),
    ("Reasoning", "Data Sufficiency", "RSN_DATA_SUFF", ["data sufficiency"]),
    ("Reasoning", "Machine Input Output", "RSN_INPUT_OUTPUT", ["machine input output"]),
    ("Reasoning", "Statement & Assumptions", "RSN_ASSUMPTIONS", ["statement and assumptions"]),
    ("Reasoning", "Statement & Conclusions / Inferences", "RSN_CONCLUSIONS", ["statement and conclusions", "drawing inferences"]),
    ("Reasoning", "Statement & Arguments", "RSN_ARGUMENTS", ["statement and arguments", "strong argument", "weak argument"]),
    ("Reasoning", "Statement & Courses of Action", "RSN_COURSES", ["statement and courses of action"]),
    ("Reasoning", "Cause & Effect", "RSN_CAUSE_EFFECT", ["cause and effect"]),
    ("Reasoning", "Decision Making", "RSN_DECISION", ["decision making", "eligibility test"]),
    ("Reasoning", "Assertion & Reason", "RSN_ASSERTION", ["assertion and reason"]),
    ("Reasoning", "Clocks & Calendars", "RSN_CLOCK_CALENDAR", ["clocks", "calendars", "angle between hands", "time gained or lost", "day of the week", "leap year"]),
    ("Reasoning", "Dice & Cubes", "RSN_DICE_CUBES", ["dice", "cubes", "standard dice", "ordinary dice", "open dice", "painted cubes", "cutting of cubes"]),
    ("Reasoning", "Mirror & Water Images", "RSN_IMAGES", ["mirror images", "water images"]),
    ("Reasoning", "Paper Folding & Cutting", "RSN_PAPER_FOLD", ["paper folding", "paper cutting"]),
    ("Reasoning", "Embedded Figures & Figure Completion", "RSN_EMBEDDED", ["embedded figures", "completion of incomplete pattern"]),
    ("Reasoning", "Figure Series & Analogy", "RSN_FIG_SERIES", ["figure series", "figure analogy", "figure classification"]),
    ("Reasoning", "Counting of Figures", "RSN_COUNTING_FIG", ["counting of figures", "counting triangles", "counting squares", "counting rectangles", "counting straight lines", "counting circles"]),
    ("Reasoning", "Matrix & Rule Detection", "RSN_MATRIX", ["matrix", "rule detection"]),
    ("Reasoning", "Dot Situation & Grouping of Identical Figures", "RSN_DOT_SITUATION", ["dot situation", "grouping of identical figures"]),

    # ─── English (Expanded) ───
    ("English", "Reading Comprehension", "ENG_RC", ["reading comprehension", "passage", "unseen passage"]),
    ("English", "Cloze Test", "ENG_CLOZE", ["cloze test", "numbered gaps"]),
    ("English", "Error Spotting / Detection", "ENG_ERROR_SPOT", ["error spotting", "error detection", "find the error", "grammatical error"]),
    ("English", "Sentence Improvement / Correction", "ENG_SENT_IMPROVE", ["sentence improvement", "sentence correction", "phrase replacement"]),
    ("English", "Fill in the Blanks", "ENG_FILLERS", ["fill in the blanks", "fillers", "single fillers", "double fillers", "multiple fillers"]),
    ("English", "Para Jumbles / Sentence Rearrangement", "ENG_PARA_JUMBLES", ["para jumbles", "sentence rearrangement", "jumbled sentences", "pqrs"]),
    ("English", "Synonyms & Antonyms", "ENG_VOCAB_SYN_ANT", ["synonyms", "antonyms", "same meaning", "opposite meaning", "vocabulary"]),
    ("English", "One Word Substitution", "ENG_VOCAB_OWS", ["one word substitution", "vocabulary"]),
    ("English", "Idioms & Phrases", "ENG_VOCAB_IDIOMS", ["idioms and phrases", "vocabulary"]),
    ("English", "Spelling Tests / Misspelt Words", "ENG_VOCAB_SPELLING", ["spelling test", "misspelled words", "correctly spelt words", "vocabulary"]),
    ("English", "Active & Passive Voice", "ENG_GRAMMAR_VOICE", ["active and passive voice", "voice change"]),
    ("English", "Direct & Indirect Speech (Narration)", "ENG_GRAMMAR_NARRATION", ["direct and indirect speech", "narration", "reported speech"]),
    ("English", "Nouns & Pronouns", "ENG_GRAMMAR_NOUN_PRONOUN", ["noun", "pronoun", "types of noun", "types of pronoun", "rules of noun", "rules of pronoun"]),
    ("English", "Adjectives & Degrees of Comparison", "ENG_GRAMMAR_ADJECTIVE", ["adjective", "degrees of comparison", "rules of adjective"]),
    ("English", "Verbs & Tenses", "ENG_GRAMMAR_VERB_TENSE", ["verb", "tenses", "rules of verb", "rules of tenses", "present tense", "past tense", "future tense"]),
    ("English", "Adverbs", "ENG_GRAMMAR_ADVERB", ["adverb", "types of adverb", "rules of adverb"]),
    ("English", "Prepositions", "ENG_GRAMMAR_PREPOSITION", ["preposition", "fixed prepositions", "rules of preposition"]),
    ("English", "Conjunctions", "ENG_GRAMMAR_CONJUNCTION", ["conjunction", "correlative conjunctions", "rules of conjunction"]),
    ("English", "Articles & Determiners", "ENG_GRAMMAR_ARTICLE", ["article", "determiners", "a an the", "omission of article"]),
    ("English", "Subject-Verb Agreement", "ENG_GRAMMAR_SVA", ["subject-verb agreement", "syntax"]),
    ("English", "Conditionals & Question Tags", "ENG_GRAMMAR_CONDITIONAL", ["conditional sentences", "question tags"]),
    ("English", "Phrasal Verbs", "ENG_VOCAB_PHRASAL_VERBS", ["phrasal verbs", "vocabulary"]),
    ("English", "Word Usage / Vocabulary Context", "ENG_VOCAB_USAGE", ["word usage", "vocabulary in context", "confusing words", "homonyms"]),
    ("English", "Sentence Completion", "ENG_SENT_COMPLETE", ["sentence completion"]),
    ("English", "Paragraph Completion", "ENG_PARA_COMPLETE", ["paragraph completion"]),
    ("English", "Odd Sentence Out", "ENG_ODD_SENTENCE", ["odd sentence out"]),
    ("English", "Word Swap / Match the Column", "ENG_WORD_SWAP", ["word swap", "match the column"]),

    # ─── Computer Knowledge (Expanded) ───
    ("Computer Knowledge", "Introduction & History of Computers", "COMP_INTRO_HIST", ["history of computers", "generations of computers", "types of computers", "characteristics of computers"]),
    ("Computer Knowledge", "Computer Hardware & Architecture", "COMP_HARDWARE", ["computer hardware", "architecture", "cpu", "alu", "cu", "registers", "motherboard", "ports", "buses"]),
    ("Computer Knowledge", "Input & Output Devices", "COMP_IO_DEVICES", ["input devices", "output devices", "keyboard", "mouse", "monitor", "printer", "scanner"]),
    ("Computer Knowledge", "Computer Memory & Storage", "COMP_MEMORY", ["computer memory", "primary memory", "secondary memory", "ram", "rom", "cache", "hard disk", "ssd", "optical disks", "magnetic tape", "memory units"]),
    ("Computer Knowledge", "Computer Software", "COMP_SOFTWARE", ["computer software", "system software", "application software", "utility software", "open source software", "proprietary software", "firmware"]),
    ("Computer Knowledge", "Operating Systems", "COMP_OS", ["operating system", "os", "functions of os", "types of os", "windows", "linux", "unix", "mac os", "android", "ios", "ms dos"]),
    ("Computer Knowledge", "MS Windows", "COMP_WINDOWS", ["ms windows", "windows os", "features of windows", "windows shortcuts"]),
    ("Computer Knowledge", "MS Office - General & Word", "COMP_MS_WORD", ["ms office", "ms word", "word processing", "features of word", "word shortcuts", "file extensions"]),
    ("Computer Knowledge", "MS Office - Excel", "COMP_MS_EXCEL", ["ms excel", "spreadsheets", "features of excel", "excel formulas", "excel functions", "excel shortcuts"]),
    ("Computer Knowledge", "MS Office - PowerPoint & Access", "COMP_MS_PPT_ACCESS", ["ms powerpoint", "presentation software", "ppt shortcuts", "ms access", "database software"]),
    ("Computer Knowledge", "Database Management Systems (DBMS)", "COMP_DBMS", ["dbms", "database", "rdbms", "sql", "keys in dbms", "normalization", "database models"]),
    ("Computer Knowledge", "Data Communication & Networking", "COMP_NETWORKING", ["computer networks", "networking concepts", "types of networks", "lan", "wan", "man", "pan", "network topologies", "network devices", "hub", "switch", "router", "modem", "osi model", "tcp ip model"]),
    ("Computer Knowledge", "Internet & Web Technologies", "COMP_INTERNET", ["internet", "web technologies", "www", "web browser", "search engine", "email", "url", "protocols", "http", "ftp", "smtp", "pop3", "imap", "ip address", "dns", "html", "xml"]),
    ("Computer Knowledge", "Computer Security & Cyber Crimes", "COMP_SECURITY", ["computer security", "cyber security", "malware", "virus", "worm", "trojan", "ransomware", "spyware", "phishing", "spoofing", "firewall", "antivirus", "cryptography", "digital signature", "cyber laws"]),
    ("Computer Knowledge", "Number Systems & Logic Gates", "COMP_NUM_SYS_LOGIC", ["number systems", "binary", "octal", "decimal", "hexadecimal", "number conversions", "logic gates", "and", "or", "not", "nand", "nor", "xor", "xnor", "boolean algebra"]),
    ("Computer Knowledge", "Programming Concepts & Languages", "COMP_PROGRAMMING", ["programming languages", "low level languages", "high level languages", "assembler", "compiler", "interpreter", "c", "c++", "java", "python", "algorithms", "flowcharts", "data structures"]),
    ("Computer Knowledge", "Abbreviations & File Extensions", "COMP_ABBREV_EXT", ["computer abbreviations", "acronyms", "file extensions", "computer terminology"]),
    ("Computer Knowledge", "Emerging Technologies", "COMP_EMERGING_TECH", ["emerging technologies", "artificial intelligence", "ai", "machine learning", "ml", "internet of things", "iot", "cloud computing", "blockchain", "big data", "virtual reality", "vr", "augmented reality", "ar"]),

    # ─── Current Affairs (Expanded) ───
    ("Current Affairs", "National News & Events", "CA_NATIONAL", ["national news", "national events", "india news"]),
    ("Current Affairs", "International News & Events", "CA_INTERNATIONAL", ["international news", "international events", "world news", "global affairs"]),
    ("Current Affairs", "State News & Events", "CA_STATES", ["state news", "state events", "regional news"]),
    ("Current Affairs", "Economy & Banking News", "CA_ECONOMY_BANKING", ["economy news", "banking news", "financial news", "rbi news", "business news"]),
    ("Current Affairs", "Science & Technology News", "CA_SCIENCE_TECH", ["science and technology news", "space news", "isro news", "defence news", "drdo news", "health news", "it news"]),
    ("Current Affairs", "Persons in News (Appointments, Obituaries)", "CA_PERSONS", ["persons in news", "appointments", "resignations", "obituaries", "famous personalities"]),
    ("Current Affairs", "Awards, Honours & Prizes", "CA_AWARDS", ["awards", "honours", "prizes", "nobel prize", "national film awards", "padma awards", "sports awards"]),
    ("Current Affairs", "Sports News & Events", "CA_SPORTS", ["sports news", "sports events", "olympics", "asian games", "commonwealth games", "cricket", "football", "tennis", "tournaments", "trophies"]),
    ("Current Affairs", "Government Schemes, Policies & Campaigns", "CA_SCHEMES_POLICIES", ["government schemes", "policies", "campaigns", "yojanas", "initiatives", "portals", "apps"]),
    ("Current Affairs", "Summits, Conferences & Meetings", "CA_SUMMITS", ["summits", "conferences", "meetings", "g20", "asean", "saarc", "brics", "sco"]),
    ("Current Affairs", "Reports, Indices & Rankings", "CA_REPORTS_INDICES", ["reports", "indices", "rankings", "india's rank", "global indices", "state rankings"]),
    ("Current Affairs", "Important Days, Dates & Themes", "CA_DAYS_THEMES", ["important days", "dates", "themes", "national days", "international days"]),
    ("Current Affairs", "Books & Authors", "CA_BOOKS_AUTHORS", ["books and authors", "recent books", "autobiographies"]),
    ("Current Affairs", "Defence Exercises & Operations", "CA_DEFENCE_EX", ["defence exercises", "military exercises", "naval exercises", "air force exercises", "military operations"]),
    ("Current Affairs", "Agreements & MoUs", "CA_AGREEMENTS_MOUS", ["agreements", "mous", "memorandum of understanding", "treaties", "partnerships"]),

    # ─── General Knowledge (Expanded) ───
    ("General Knowledge", "Firsts in India (Male/Female/Misc)", "GK_FIRSTS_INDIA", ["first in india", "first indian male", "first indian female", "first events in india"]),
    ("General Knowledge", "Firsts in World (Male/Female/Misc)", "GK_FIRSTS_WORLD", ["first in world", "first person in world", "first events in world"]),
    ("General Knowledge", "Superlatives - India (Largest, Longest, Highest)", "GK_SUPERLATIVES_INDIA", ["superlatives india", "largest in india", "longest in india", "highest in india", "smallest in india"]),
    ("General Knowledge", "Superlatives - World (Largest, Longest, Highest)", "GK_SUPERLATIVES_WORLD", ["superlatives world", "largest in world", "longest in world", "highest in world", "smallest in world"]),
    ("General Knowledge", "Countries, Capitals, Currencies & Parliaments", "GK_COUNTRIES", ["countries", "capitals", "currencies", "parliaments", "official languages of countries"]),
    ("General Knowledge", "International Organizations & Headquarters", "GK_INTL_ORG", ["international organizations", "headquarters", "un", "un agencies", "wto", "who", "imf", "world bank", "saarc", "asean", "nato"]),
    ("General Knowledge", "National Organizations & Institutions", "GK_NAT_ORG", ["national organizations", "institutions", "research institutes", "research centers in india", "headquarters in india"]),
    ("General Knowledge", "Important Boundary Lines", "GK_BOUNDARY_LINES", ["boundary lines", "international boundaries", "radcliffe line", "macmahon line", "durand line"]),
    ("General Knowledge", "National Symbols of India", "GK_NAT_SYMBOLS", ["national symbols", "national flag", "national anthem", "national song", "national emblem", "national animal", "national bird"]),
    ("General Knowledge", "Major Rivers, Dams & Hydro Projects in India", "GK_RIVERS_DAMS_IND", ["rivers in india", "dams in india", "hydroelectric projects", "multipurpose river valley projects", "cities on river banks"]),
    ("General Knowledge", "Major Lakes & Waterfalls in India", "GK_LAKES_WATERFALLS_IND", ["lakes in india", "waterfalls in india"]),
    ("General Knowledge", "National Parks, Wildlife Sanctuaries & Biosphere Reserves", "GK_NATIONAL_PARKS", ["national parks", "wildlife sanctuaries", "biosphere reserves", "tiger reserves", "elephant reserves", "bird sanctuaries"]),
    ("General Knowledge", " UNESCO World Heritage Sites in India", "GK_UNESCO_SITES", ["unesco sites", "world heritage sites in india"]),
    ("General Knowledge", "Famous Temples, Monuments & Places in India", "GK_TEMPLES_MONUMENTS", ["famous temples", "monuments", "historical places", "tourist places", "forts", "palaces"]),
    ("General Knowledge", "Indian Art, Culture & Classical Dances", "GK_ART_CULTURE", ["indian art", "indian culture", "classical dances", "bharatanatyam", "kathak", "kathakali", "kuchipudi", "odissi", "manipuri", "mohiniyattam", "sattriya"]),
    ("General Knowledge", "Folk Dances & Festivals of India", "GK_FOLK_DANCES_FESTIVALS", ["folk dances", "regional dances", "festivals of india", "harvest festivals", "fairs", "melas"]),
    ("General Knowledge", "Indian Music & Musical Instruments", "GK_MUSIC_INSTRUMENTS", ["indian music", "hindustani music", "carnatic music", "musical instruments", "famous musicians", "maestros"]),
    ("General Knowledge", "Paintings, Martial Arts & Crafts of India", "GK_PAINTINGS_MARTIAL", ["indian paintings", "madhubani", "warli", "phad", "martial arts", "kalaripayattu", "thang ta", "handicrafts"]),
    ("General Knowledge", "Major Tribes of India & World", "GK_TRIBES", ["tribes of india", "world tribes", "indigenous people"]),
    ("General Knowledge", "Important Inventions & Discoveries", "GK_INVENTIONS_DISCOVERIES", ["inventions", "inventors", "discoveries", "discoverers", "scientific inventions", "medical discoveries"]),
    ("General Knowledge", "Famous Books & Authors (Historical & Classic)", "GK_BOOKS_AUTHORS_HIST", ["famous books", "authors", "historical books", "classic literature", "ancient texts"]),
    ("General Knowledge", "Important Awards & Honors (History & Static)", "GK_AWARDS_STATIC", ["important awards", "nobel prize history", "bharat ratna", "khel ratna", "gallantry awards", "sahitya akademi", "jnanpith", "oscar history"]),
    ("General Knowledge", "Sports - Terms, Trophies, Cups & Stadiums", "GK_SPORTS_STATIC", ["sports terms", "sports trophies", "sports cups", "stadiums", "number of players", "sports measurements", "olympic history", "asian games history", "commonwealth games history", "world cup history"]),
    ("General Knowledge", "Important Places in the World", "GK_PLACES_WORLD", ["important places world", "famous monuments world", "wonders of the world"]),
    ("General Knowledge", "Major Deserts, Grasslands & Straits of the World", "GK_DESERTS_GRASSLANDS", ["world deserts", "world grasslands", "world straits", "world plateaus"]),
    ("General Knowledge", "Major Rivers, Lakes & Waterfalls of the World", "GK_RIVERS_WORLD", ["world rivers", "world lakes", "world waterfalls", "cities on banks of world rivers"]),
    ("General Knowledge", "Sobriquets (Nicknames of Places & Persons)", "GK_SOBRIQUETS", ["sobriquets", "nicknames of places", "nicknames of eminent persons", "geographical epithets"]),
    ("General Knowledge", "Important Instruments & Their Uses", "GK_INSTRUMENTS_USES", ["scientific instruments", "measuring instruments", "barometer", "hygrometer", "lactometer"]),
    ("General Knowledge", "Prominent Personalities & Leaders (Historical)", "GK_PERSONALITIES_HIST", ["prominent personalities", "historical leaders", "social reformers", "freedom fighters", "scientists", "philosophers"]),
    ("General Knowledge", "Miscellaneous Static GK", "GK_MISC", ["miscellaneous gk", "static gk general", "other facts"])
]
